#!/bin/bash

function echo_help() {
        echo "USAGE:
    license-add <LICENSE> [OUTPUT_FILE]   Add LICENSE to OUTPUT_FILE xor LICENSE
    license-add help                      Print this help message"
}

if [ "$1" == "help" ]; then
        echo_help;
elif [ -f ~/.config/license-add/$1 ]; then
        if [ "$2" == "" ]; then
                cp ~/.config/license-add/$1 LICENSE;
        else
                cp ~/.config/license-add/$1 $2;
        fi
else
        echo "Invalid license:" $1;
        echo_help;
fi
